name: PR-kemon
description: Adds a comment thanking the author when a PR is opened, with bonus pokemon information
runs:
  using: node12
  main: index.js
branding:
  icon: message-circle
  color: red
